//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalWaitAreaShow
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATI_OUT_VISIT_FZ
    {
        public string FZLSH { get; set; }
        public string FZXH { get; set; }
        public string MZLSH { get; set; }
        public string PATINAME { get; set; }
        public string PATIID { get; set; }
        public string HJBZ { get; set; }
        public Nullable<System.DateTime> FZSJ { get; set; }
        public string FZYS { get; set; }
        public string FZKS { get; set; }
        public string FZLX { get; set; }
        public string FZRY { get; set; }
        public string SJLX { get; set; }
        public string YYSJ { get; set; }
        public Nullable<System.DateTime> ZFSJ { get; set; }
        public string ZFRY { get; set; }
        public string HJSX { get; set; }
        public string RESTYPEID { get; set; }
        public string LOCORGID { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public string INPUTEMPID { get; set; }
        public string VISITTYPE { get; set; }
        public Nullable<System.DateTime> CALLTIME { get; set; }
        public string RESID { get; set; }
        public string BILLFLAG { get; set; }
        public string YSXH { get; set; }
        public string DUTY_ID { get; set; }
        public string RSRCTYPEID { get; set; }
        public string RSRCTYPE { get; set; }
        public string FZNOTICE { get; set; }
        public string SERIALNUMBER { get; set; }
        public string expert_flag { get; set; }
        public string duty_mae { get; set; }
        public Nullable<int> TRIAGE_FLAG { get; set; }
    }
}
